---

apiVersion: v1
kind: Namespace
metadata:
  name: covidtweetbr

---
  
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: covidtweetbr-run
  namespace: covidtweetbr
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: aksdemoimages-acr-auth
          containers:
          - name: run
            image: "aksdemoimages.azurecr.io/covidtweetbr:latest"
          restartPolicy: OnFailure

#EOF